name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # ou a branch que desejar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e Push da imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: tiagotas/conversao-distancia:v1-slim
